language: python
python:
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "3.4"

virtualenv:
  system_site_packages: true

sudo: required
dist: trusty

cache:
  - pip

addons:
  postgresql: "9.3"
  apt:
    packages:
      - apache2
      - libapache2-mod-wsgi

branches:
  except:
    - none

env:
  - DB=sqlite
    # SPOOF_MANUAL_MIGRATIONS is used to tell the migration scripts that they
    # should make up data that would otherwise require manual intervention;
    # this is important for the migration tests.
  - DB=postgres SPOOF_MANUAL_MIGRATIONS=true

install:
  # A dependency might use new pip syntax; upgrade to prevent breakage. See #771
  - pip install --upgrade pip
  - sh -e ci/apache/install.sh
  - sh -e ci/keystone/install.sh

script:
  - sh -e ci/pycodestyle_tests.sh
  - sh -e ci/pylint_tests.sh
  - sh -e ci/no_trailing_whitespace.sh
  - sh -e ci/run_unit_tests.sh
  - sh -e ci/apache/run_integration_tests.sh
  - sh -e ci/keystone/run_integration_tests.sh
  - sh -e ci/deployment-mock-networks/run_integration_tests.sh
  - coverage report -m

after_success:
  - coveralls
